GIVE_LINK = ('Пришлите мне ссылку на список фотографий с picsum.photos, например: '
             'https://picsum.photos/v2/list?page=2&limit=100')
WELCOME_MESSAGE = f'Привет, это онбординг. {GIVE_LINK}'
INVALID_LINK = 'Ссылка некорректна. Вы можете добавить фотографии из меню по кнопке ниже.'
RETRY_LINK = 'Ссылка некорректна. Попробуйте ещё раз.'
SAVES_SUCCESSFULLY = 'Фотографии успешно сохранены.'
PICTURE_DELETED = 'Фотография была успешно удалена.'

MAIN_MENU = 'Главное меню.'
ADD_PICTURES = '➕Добавить фотографии'
PICTURE_LIST = '📃Список фотографий'
GET_PICTURE_TABLE = '📋Получить таблицу фото'
TO_MAIN = '🔙В меню'
DELETE = '🗑Удалить'
BACK = '🔙Назад'
YES = '✅Да'
NO = '❎Нет'

ADD_PICTURE_BUTTON = 'add_picture_button'
PICTURE_LIST_BUTTON = 'picture_list_button'
PICTURE_TABLE_BUTTON = 'photo_table_button'
TO_MAIN_BUTTON = 'to_main_button'
DELETE_BUTTON = 'delete_button'
BACK_BUTTON = 'back_button'
YES_BUTTON = 'yes_button'
NO_BUTTON = 'no_button'

EMPTY_PICTURE = 'bot/utils/empty_photo.png'
TABLE_PICTURE = 'table.csv'
